CURL = curl
WGET = wget
SAVEURL = $(WGET) -O
GIT = git

all: data build

clean:

updatenightly: build-index
	$(CURL) -sSLf https://gist.githubusercontent.com/wakaba/34a71d3137a52abb562d/raw/gistfile1.txt | sh
	$(GIT) add bin/modules
	perl local/bin/pmbp.pl --update
	$(GIT) add config
	$(CURL) -sSLf https://raw.githubusercontent.com/wakaba/ciconfig/master/ciconfig | RUN_GIT=1 REMOVE_UNUSED=1 perl
	#
	$(MAKE) updatebyhook

updatebyhook: data
#	$(GIT) add 

## ------ Setup ------

PERL = ./perl \
    -Ibin/modules/json-ps/lib \
    -Ibin/modules/perl-web-encodings/lib

deps: git-submodules pmbp-install

git-submodules:
	$(GIT) submodule update --init

local/bin/pmbp.pl:
	mkdir -p local/bin
	$(CURL) -s -S -L -f https://raw.githubusercontent.com/pawjy/perl-setupenv/master/bin/pmbp.pl > $@
pmbp-upgrade: local/bin/pmbp.pl
	perl local/bin/pmbp.pl --update-pmbp-pl
pmbp-update: git-submodules pmbp-upgrade
	perl local/bin/pmbp.pl --update
pmbp-install: pmbp-upgrade
	perl local/bin/pmbp.pl --install \
            --create-perl-command-shortcut perl

local/opentype.js:
	$(SAVEURL) $@ https://raw.githubusercontent.com/manakai/opentypejs/refs/heads/master/dist/opentype.js

local/fonts/frq0.ttf:
	mkdir -p local/fonts
	$(SAVEURL) $@ https://fonts.suikawiki.org/frq/frq0.ttf

## ------ Build ------

build: build-index data

data: deps data-main

data-main: 

build-github-pages: deps build-gp-main build-gp-index build-gp-cleanup

build-gp-main:
	mkdir -p local current
	docker run -v `pwd`/local:/local --user `id --user` quay.io/suikawiki/swfonts:swcf cp -R /app/fonts/swir /local/swir
	docker run -v `pwd`/local:/local --user `id --user` quay.io/suikawiki/swir:data-main cp -R /app/indexes /local/swir-indexes
	mv local/swir current/swir
	mv local/swir-indexes current/swir-indexes
build-gp-cleanup:
	rm -fr ./bin/modules ./modules ./local ./deps
	rm config/perl/libs.txt

build-for-docker: build-for-docker-from-old \
    local/swir local/swcfk
	-chmod ugo+r -R local/swir
	-chmod ugo+r -R local/swcfk

build-for-docker-from-old:
	mkdir -p local
	docker run -v `pwd`/local:/local --user `id --user` quay.io/suikawiki/swfonts:swcf cp -R /app/fonts/swir /local/swir || mkdir -p local/swir
	docker run -v `pwd`/local:/local --user `id --user` quay.io/suikawiki/swfonts:swcf cp -R /app/fonts/swcfk /local/swcfk || mkdir -p local/swcfk

## <https://suikawiki.github.io/swcf/current/swir/list.json>
##    List of regions.
## <https://suikawiki.github.io/swcf/current/swir/ep.json>
##    Binarized glyph data.
## <https://suikawiki.github.io/swcf/current/swir/gmap.json>
##    gmap.json for gh/manakai/data-chars charrels and kgmap.
## <https://suikawiki.github.io/swcf/current/swir-indexes/list-1.txt>
## <https://suikawiki.github.io/swcf/current/swir-indexes/licenses.txt>
##    List of region image data, generated by gh/suikawiki/swir-generator.

local/swdata-swir-ids.txt:
	$(CURL) -sSLf https://raw.githubusercontent.com/suikawiki/extracted/refs/heads/master/data/extracted/swir-ids.txt > $@
local/swdata-swir-list.txt: local/swdata-swir-ids.txt 
	cat local/swdata-swir-ids.txt | \
	awk '{ q = int($$1 / 1000); r = $$1 % 1000; printf "local/data/ids/%d/%d.txt\n", q, r }' > $@
local/swir: local-swdata-repo always
	mkdir -p $@
	$(MAKE) $@/list.json $@/ep.json $@/gmap.txt $@/gmap.json
local/swir/list.json: bin/swir-list.pl local/swdata-swir-list.txt
	$(PERL) bin/swir-list.pl local/swdata-swir-list.txt > $@
local/swir/gmap.txt: bin/swir-list-to-gmap.pl local/swir/list.json
	$(PERL) $< local/swir/list.json > $@
local/swir/gmap.json: bin/gmap.pl local/swir/gmap.txt
	$(PERL) $< local/swir/gmap.txt > $@
local/swir/ep.json: js/*.js local/swir/list.json
	ls -l $@ || echo '{}' > $@
	docker run -i \
            -v `pwd`/js:/app \
            -v `pwd`/local/swir/list.json:/app/local/list.json \
            -v `pwd`/local/swir/ep.json:/app/local/paths.json \
	    -w /app \
	    node bash -c 'npm install canvas && node construct-ep-json.js'
	ls -l $@

local/swcfk: always
	mkdir -p $@
	$(MAKE) $@/kana3b.ttf
local/swir-gmap.json: local/swir/gmap.json
	cp $< $@
local/swcfk/kana3-kgmap.json: bin/kgmap.pl config/kana3-config.pl \
    local/swir-gmap.json
	GMAP_PATH=../local/ $(PERL) $< config/kana3-config.pl
local/swcfk/kana3b.ttf: js/kggenerate.js js/otwriter.js local/opentype.js \
    local/swcfk/kana3-kgmap.json \
    local/fonts/frq0.ttf local/swir/ep.json
	docker run -i -v `pwd`:/app \
	    -v `pwd`/js:/app \
	    -v `pwd`/local/swcfk:/app/swcfk \
	    -v `pwd`:/app/data \
	    -v `pwd`/local/opentype.js:/app/opentype.js \
	    -v `pwd`/local/fonts:/app/fonts \
	    node bash -c 'cd /app && node kggenerate.js swcfk/kana3-kgmap.json 2'

local-swdata-repo:
	$(GIT) clone --depth 1 https://github.com/suikawiki/suikawiki-data local/data || \
	(cd local/data && $(GIT) fetch --depth 1 origin master && $(GIT) checkout origin/master)

build-index: deps 

build-gp-index: 

## ------ Tests ------

test: test-main test-deps

test-deps: deps

test-main:

always:

## License: Public Domain.
