CURL = curl
WGET = wget
SAVEURL = $(WGET) -O
GIT = git

all: data build

clean:

updatenightly: build-index
	$(CURL) -sSLf https://gist.githubusercontent.com/wakaba/34a71d3137a52abb562d/raw/gistfile1.txt | sh
	$(GIT) add bin/modules
	perl local/bin/pmbp.pl --update
	$(GIT) add config
	$(CURL) -sSLf https://raw.githubusercontent.com/wakaba/ciconfig/master/ciconfig | RUN_GIT=1 REMOVE_UNUSED=1 perl
	#
	$(MAKE) updatebyhook

updatebyhook: data
#	$(GIT) add 

## ------ Setup ------

PERL = ./perl

deps: git-submodules pmbp-install

git-submodules:
	$(GIT) submodule update --init

local/bin/pmbp.pl:
	mkdir -p local/bin
	$(CURL) -s -S -L -f https://raw.githubusercontent.com/pawjy/perl-setupenv/master/bin/pmbp.pl > $@
pmbp-upgrade: local/bin/pmbp.pl
	perl local/bin/pmbp.pl --update-pmbp-pl
pmbp-update: git-submodules pmbp-upgrade
	perl local/bin/pmbp.pl --update
pmbp-install: pmbp-upgrade
	perl local/bin/pmbp.pl --install \
            --create-perl-command-shortcut perl

## ------ Build ------

build: build-index data

data: deps data-main

data-main: 

build-github-pages: deps build-gp-main build-gp-index build-gp-cleanup

build-gp-main:
	mkdir -p local current
	docker run -v `pwd`/local:/local --user `id --user` quay.io/suikawiki/swfonts:swcf cp -R /app/fonts/swir /local/swir
	docker run -v `pwd`/local:/local --user `id --user` quay.io/suikawiki/swir:data-main cp -R /app/indexes /local/swir-indexes
	mv local/swir current/swir
	mv local/swir-indexes current/swir-indexes
build-gp-cleanup:
	rm -fr ./bin/modules ./modules ./local ./deps
	rm config/perl/libs.txt

build-for-docker: build-for-docker-from-old \
    local/swir
	-chmod ugo+r -R local/swir

build-for-docker-from-old:
	mkdir -p local
	docker run -v `pwd`/local:/local --user `id --user` quay.io/suikawiki/swfonts:swcf cp -R /app/fonts/swir /local/swir || mkdir -p local/swir

## <https://suikawiki.github.io/swcf/current/swir/list.json>
##    List of regions.
## <https://suikawiki.github.io/swcf/current/swir/ep.json>
##    Binarized glyph data.
## <https://suikawiki.github.io/swcf/current/swir-indexes/list-1.txt>
## <https://suikawiki.github.io/swcf/current/swir-indexes/licenses.txt>
##    List of region image data, generated by gh/suikawiki/swir-generator.

local/swdata-swir-ids.txt:
	$(CURL) -sSLf https://raw.githubusercontent.com/suikawiki/extracted/refs/heads/master/data/extracted/swir-ids.txt > $@
local/swdata-swir-list.txt: local/swdata-swir-ids.txt 
	cat local/swdata-swir-ids.txt | \
	awk '{ q = int($$1 / 1000); r = $$1 % 1000; printf "local/data/ids/%d/%d.txt\n", q, r }' > $@
local/swir: local-swdata-repo always
	mkdir -p $@
	$(MAKE) $@/list.json $@/ep.json
local/swir/list.json: bin/swir-list.pl local/swdata-swir-list.txt
	$(PERL) bin/swir-list.pl local/swdata-swir-list.txt > $@/list.json
local/swir/ep.json: js/*.js local/swir/list.json
	ls -l $@ || echo '{}' > $@
	docker run -i \
            -v `pwd`/js:/app \
            -v `pwd`/local/swir/list.json:/app/local/list.json \
            -v `pwd`/local/swir/ep.json:/app/local/paths.json \
	    -w /app \
	    node node construct-ep-json.js
	ls -l $@

local-swdata-repo:
	$(GIT) clone --depth 1 https://github.com/suikawiki/suikawiki-data local/data || \
	(cd local/data && $(GIT) fetch --depth 1 origin master && $(GIT) checkout origin/master)

build-index: deps 

build-gp-index: 

## ------ Tests ------

test: test-main test-deps

test-deps: deps

test-main:

always:

## License: Public Domain.
